import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigtion from "./Components/Navigation/Navigtion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <Navigtion />
        </>
        <div className="pb-20 pt-28">{children}</div>
      </body>
    </html>
  );
}
